{
 "title": "Home",
 "time": { "from": "now", "to": "now" },
 "templating": {
  "list": [
   { "name": "Account", "query": { "query": "label_values(account_id)" } },
   { "name": "region", "query": { "query": "label_values(region)" } },
   {
    "name": "Project",
    "query": {
     "query": "label_values(project_spend_project)"
    }
   },
   { "name": "Month", "query": { "query": "label_values(month)" } }
  ]
 },
 "panels": [
  {
   "title": "Tracking Total Costs Across Multiple Accounts",
   "type": "barchart",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(month) (Total_Account_Cost{month=~\"$Month\", job=\"Total_Account_Cost\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Account Account Cost for last 3 months",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "Total_Account_Cost{job=\"Total_Account_Cost\", account_id=\"$Account\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Project Spend Cost",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "Project_Spend_Cost{job=\"Project-Spend-Cost\", project_spend_project=\"$Project\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 most expensive services ",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "Expensive_Services_Detail{job=\"Most_Expensive_Services\", region=\"$region\", account=\"$Account\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}